{{ if eq .Values.environment "local" -}}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer
  {{- with .Values.issuer.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ca:
    secretName: ca-key-pair
{{- end }}