#controller:
#  replicas: 1
#
#server:
#  replicas: 1
#  extraArgs:
#    - --insecure
#  ingress:
#    enabled: true
#    annotations:
#      cert-manager.io/cluster-issuer: ca-issuer
#    hosts:
#      - argo.sntlk.net
#    tls:
#      - hosts:
#          - argo.sntlk.net
#        secretName: ingress-cert
#
#  config:
#    resource.customizations.health.argoproj.io_Application: |
#      hs = {}
#      hs.status = "Progressing"
#      hs.message = ""
#      if obj.status ~= nil then
#        if obj.status.health ~= nil then
#          hs.status = obj.status.health.status
#          if obj.status.health.message ~= nil then
#            hs.message = obj.status.health.message
#          end
#        end
#      end
#      return hs
#
#redis:
#  image:
#    repository: docker.io/library/redis
#
#repoServer:
#  replicas: 1
#
#applicationSet:
#  replicaCount: 1
#
#metrics:
#  enabled: true
