environment: local
applications:
  openebs:
    enabled: true
  crossplane:
    enabled: true
  cert_manager:
    enabled: true
  traefik:
    enabled: true
  argocd:
    enabled: true
  argo_workflows:
    enabled: true
  zitadel:
    enabled: true
  drone:
    enabled: true
  mattermost:
    enabled: true