environment: local
applications:
  longhorn:
    enabled: true
  cert_manager:
    enabled: true
  traefik:
    enabled: true
  argocd:
    enabled: true
  zitadel:
    enabled: true
  drone:
    enabled: true
  mattermost:
    enabled: true