keys:
  - &age age1z3zn777dkjggzwlfazzl8nrh6cvmt4zhxwne0dyqpzhzgsvkk5yq4wlry6
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *age
  - path_regex: secrets/kubernetes/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *age