{{ if .Values.applications.openebs.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  labels:
    {{- include "argo-system.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: default
  sources:
    - repoURL: https://openebs.github.io/charts
      targetRevision: '3.6.0'
      chart: openebs
      helm:
        valueFiles:
          - $values/kubernetes/values/{{ .Values.environment }}/openebs.values.yaml
    - repoURL: https://codeberg.org/istimaldar/noic.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: openebs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true 
{{- end }}
{{ if .Values.applications.cert_manager.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  labels:
    {{- include "argo-system.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      targetRevision: '1.11.1'
      chart: cert-manager
      helm:
        valueFiles:
          - $values/kubernetes/values/{{ .Values.environment }}/cert-manager.values.yaml
    - repoURL: https://codeberg.org/istimaldar/noic.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuer
  labels:
    {{- include "argo-system.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  project: default
  sources:
    - repoURL: https://codeberg.org/istimaldar/noic.git
      targetRevision: HEAD
      path: kubernetes/charts/cert-manager-issuer
      helm:
        parameters:
          - name: environment
            value: {{ .Values.environment | quote }}
        valueFiles:
          - ../../values/{{ .Values.environment }}/cert-manager-issuer.values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true 
{{- end }}
{{ if .Values.applications.traefik.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  labels:
    {{- include "argo-system.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: default
  sources:
    - repoURL: https://traefik.github.io/charts
      targetRevision: '22.1.0'
      chart: traefik
      helm:
        valueFiles:
          - $values/kubernetes/values/{{ .Values.environment }}/traefik.values.yaml
    - repoURL: https://codeberg.org/istimaldar/noic.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true 
{{- end }}
{{ if .Values.applications.argocd.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  labels:
    {{- include "argo-system.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      targetRevision: '5.29.1'
      chart: argo-cd
      helm:
        valueFiles:
          - $values/kubernetes/values/{{ .Values.environment }}/argo-cd.values.yaml
    - repoURL: https://codeberg.org/istimaldar/noic.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true 
{{- end }}
{{ if .Values.applications.zitadel.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zitadel-cockroachdb
  labels:
    {{- include "argo-system.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: default
  sources:
    - repoURL: https://charts.cockroachdb.com/
      targetRevision: '10.0.8'
      chart: cockroachdb
      helm:
        valueFiles:
          - $values/kubernetes/values/{{ .Values.environment }}/zitadel-cockroachdb.values.yaml
    - repoURL: https://codeberg.org/istimaldar/noic.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: zitadel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zitadel
  labels:
    {{- include "argo-system.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: default
  sources:
    - repoURL: https://charts.zitadel.com
      targetRevision: '4.3.0'
      chart: zitadel
      helm:
        valueFiles:
          - $values/kubernetes/values/{{ .Values.environment }}/zitadel.values.yaml
    - repoURL: https://codeberg.org/istimaldar/noic.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: zitadel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true 
{{- end }}
{{ if .Values.applications.mattermost.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mattermost
  labels:
    {{- include "argo-system.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  sources:
    - repoURL: https://helm.mattermost.com
      targetRevision: '6.6.22'
      chart: mattermost-team-edition
      helm:
        valueFiles:
          - $values/kubernetes/values/{{ .Values.environment }}/mattermost.values.yaml
    - repoURL: https://codeberg.org/istimaldar/noic.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: mattermost
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true 
{{- end }}