{{- $environment := .Values.environment -}}
{{ range $name, $config := .Values.applications -}}
{{ if $config.enabled -}}
{{ $local := $config.local | default false -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $name | quote }}
  labels:
    {{- include "argo-system.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $config.sync_wave | quote }}
spec:
  project: default
  sources:
    - repoURL: {{ $config.repo | quote }}
      targetRevision: {{ $config.version | quote }}
      {{ if $local }}path{{ else }}chart{{ end }}: {{ $config.chart | quote }}
      helm:
        valueFiles:
          - $values/kubernetes/values/{{ $name }}.values.yaml
          - $values/kubernetes/values/{{ $environment }}/{{ $name }}.values.yaml
    - repoURL: https://github.com/istimaldar/noic.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $config.namespace | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
{{ end }}
{{ end }}

