{{ range $name, $config := .Values.operators -}}
{{ if $config.enabled -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $name | quote }}
  labels:
    {{- include "argo-system.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $config.sync_wave | quote }}
spec:
  project: default
  source:
    repoURL: https://github.com/istimaldar/noic.git
    targetRevision: HEAD
    path: kubernetes/charts/argo-operator
    helm:
      valuesObject:
        catalog: {{- $config.catalog | toYaml | nindent 12 }}
        subscription: {{- $config.subscription | toYaml | nindent 12 }}
        group: {{- $config.group | toYaml | nindent 12 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $config.namespace | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - Validate=false
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
{{ end }}
{{ end }}

