{{ if .Values.catalog.enabled -}}
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: {{ include "argo-operators.catalogName" . | quote }}
spec:
  sourceType: grpc
  image: {{ .Values.catalog.image | quote }}
  displayName: {{ .Values.catalog.display_name | quote }}
  publisher: {{ .Values.catalog.publisher | quote }}
{{- end }}
