apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ include "argo-operators.subscritionName" . | quote }}
spec:
  channel: {{ .Values.subscription.channel }}
  name: argocd-operator
  source: {{ include "argo-operators.subscriptionSourceName" . | quote }}
  sourceNamespace: {{ include "argo-operators.subscriptionSourceNamespace" . | quote }}
  installPlanApproval: Automatic
