amdGpu = false
stable = false
serveCache = true
listenCache = false

[monitors]
primary = "HDMI-A-2"
secondary = "DP-2"

[features.dotnet]
enable = true

[features.media_edit]
enable = true

[features.cloud]
enable = true

[features.messangers]
enable = true

[features.java]
enable = true

[features.kubernetes]
enable = true
ha = true
server = true

[extraMounts]
