amdGpu = true
stable = false

[monitors]
primary = "DP-1"
secondary = "DP-1"

[features.dotnet]
enable = true

[features.java]
enable = true

[features.python]
enable = true

[features.media_edit]
enable = true

[features.cloud]
enable = true

[features.messangers]
enable = true

[features.kubernetes]
enable = true

[features.miscellaneous]
enable = true

[extraMounts."/mnt/c"]
  device = "/dev/nvme0n1p3"
  fsType = "ntfs3"
  options = [
    "ro",
    "uid=1000"
  ]

