amdGpu = false
stable = false

[monitors]
primary = "HDMI-A-2"
secondary = "DP-2"

[features.dotnet]
enable = true

[features.java]
enable = true

[features.python]
enable = true

[features.media_edit]
enable = true

[features.cloud]
enable = true

[features.messangers]
enable = true

[features.kubernetes]
enable = true

[features.miscellaneous]
enable = true

[extraMounts]
