waybarOn = [
  "DP-2"
]
amdGpu = false
stable = false
serveCache = false
listenCache = false

[features.dotnet]
enable = true

[features.media_edit]
enable = true

[features.cloud]
enable = true

[features.messangers]
enable = true

[features.java]
enable = true

[features.kubernetes]
enable = false
ha = false
server = true

[extraMounts."/mnt/c"]
  device = "/dev/nvme0n1p3"
  fsType = "ntfs3"
  options = [
    "ro",
    "uid=1000"
  ]

