waybarOn = [
  "HDMI-A-1"
]
amdGpu = false
stable = false

[features.dotnet]
enable = false

[features.media_edit]
enable = false

[features.cloud]
enable = false

[features.messangers]
enable = false

[extraMounts]