controller:
  replicas: 1

server:
  replicas: 1
  extraArgs:
    - --insecure
  ingress:
    enabled: true
    server.ingress.annotations:
      cert-manager.io/cluster-issuer: ca-issuer
    hosts:
      - argo.local.gd
    tls:
      - hosts:
          - argo.local.gd
        secretName: ingress-cert

repoServer:
  replicas: 1

applicationSet:
  replicaCount: 1

metrics:
  enabled: true

crds:
  annotations:
    argocd.argoproj.io/sync-wave: "-2"

global:
  statefulsetAnnotations:
    argocd.argoproj.io/sync-wave: "-2"
  deploymentAnnotations:
    argocd.argoproj.io/sync-wave: "-2"
