controller:
  replicas: 1

server:
  replicas: 1
  extraArgs:
    - --insecure
  ingress:
    enabled: true
    server.ingress.annotations:
      cert-manager.io/cluster-issuer: ca-issuer
    hosts:
      - argo.local.gd
    tls:
      - hosts:
          - argo.local.gd
        secretName: myingress-cert

repoServer:
  replicas: 1

applicationSet:
  replicaCount: 1

metrics:
  enabled: true
