workflow:
  serviceAccount:
    create: true
    name: "argo-workflow"
  rbac:
    create: true
controller:
  workflowNamespaces:
    - argocd
    - zitadel
    - workflows
server:
  extraArgs:
    - --auth-mode=server
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: ca-issuer
    hosts:
      - workflows.192-168-100-5.nip.io
    pathType: Prefix
    paths:
      - /
    tls:
      - hosts:
          - workflows.192-168-100-5.nip.io
        secretName: ingress-cert
