image:
  tag: 2.16.0

ingress:
  enabled: true
  hosts:
    - host: drone.127.0.0.1.nip.io
      paths:
        - path: /
          pathType: Prefix

persistentVolume:
  enabled: false

extraSecretNamesForEnvFrom:
  - drone

env:
  DRONE_SERVER_HOST: drone.127.0.0.1.nip.io