providers:
  kubernetesIngress:
    publishedService:
      enabled: true
  kubernetesCRD:
    allowCrossNamespace: true

ports:
  traefik:
    port: 9000
    expose: true
    exposedPort: 9000
    protocol: TCP
  web:
    port: 8000
    expose: true
    exposedPort: 80
    protocol: TCP
  websecure:
    port: 8443
    expose: true
    exposedPort: 443
    protocol: TCP
    http3:
      enabled: true
    tls:
      enabled: true
      options: ""
      certResolver: ""
      domains: []
      middlewares: []
  metrics:
    port: 9100
    expose: false
    exposedPort: 9100
    protocol: TCP

deployment:
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
ingressRoute:
  dashboard:
    annotations:
      argocd.argoproj.io/sync-wave: "-3"
service:
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
persistence:
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
serviceAccountAnnotations:
  argocd.argoproj.io/sync-wave: "-3"