fullnameOverride: crdb
conf:
  single-node: true
statefulset:
  replicas: 1
storage:
  persistentVolume:
    size: 10Gi
    storageClass: openebs-hostpath
tls:
  enabled: false
  certManager: true
  certManagerIssuer:
    group: cert-manager.io
    kind: ClusterIssuer
    name: ca-issuer