zitadel:
  dbSslRootCrtSecret: ""
  dbSslClientCrtSecret: ""
  masterkey: "OlYh3S9d6lYxjRUYAPMuOPBlchKsr9Mv"
  configmapConfig:
    ExternalSecure: false
    TLS:
      Enabled: false
    Database:
      cockroach:
        User:
          SSL:
            Mode: disable
        Admin:
          SSL:
            Mode: disable
  secretConfig:
    Database:
      cockroach:
        User:
          Password: "4qU2K2SHBKw4HoPNKLAqvm6hl7iViVCv"
replicaCount: 1
