zitadel:
  dbSslRootCrtSecret: "crdb-ca-secret"
  dbSslClientCrtSecret: "crdb-client-secret"
  masterkey: "OlYh3S9d6lYxjRUYAPMuOPBlchKsr9Mv"
  configmapConfig:
    ExternalPort: 443
    ExternalDomain: zitadel.local.gd
    ExternalSecure: true
    TLS:
      Enabled: false
    FirstInstance:
      Org:
        Human:
          UserName: 'istimaldar'
          FirstName: 'istimaldar'
          LastName: 'istimaldar'
          NickName: 'istimaldar'
          DisplayName: 'istimaldar'
          Email:
            Address: 'istimaldar@gmail.com'
            Verified: true
          PreferredLanguage: en
          Password: 'Qq_12345'
    Database:
      cockroach:
        User:
          SSL:
            Mode: "verify-full"
        Admin:
          SSL:
            Mode: "verify-full"
  secretConfig:
    Database:
      cockroach:
        User:
          Username: "zitadel"
          Password: "4qU2K2SHBKw4HoPNKLAqvm6hl7iViVCv"
        Admin:
          Username: 'root'
          Password: ''
replicaCount: 1
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: ca-issuer
  hosts:
    - host: zitadel.local.gd
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - zitadel.local.gd
      secretName: ingress-cert