fullnameOverride: crdb
conf:
  single-node: true
statefulset:
  replicas: 1
storage:
  persistentVolume:
    size: 10Gi
    storageClass: openebs-hostpath
tls:
  enabled: true
  certManager: true
  certManagerIssuer:
    group: cert-manager.io
    kind: ClusterIssuer
    name: ca-issuer
init:
  provisioning:
    enabled: true
    users:
      - name: zitadel
        password: "4qU2K2SHBKw4HoPNKLAqvm6hl7iViVCv"
    databases:
      - name: zitadel
        owners:
          - zitadel